/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package harness

import (
	"fmt"
	"strings"

	clawv1 "github.com/clawbernetes/operator/api/v1"
)

// HermesHarness implements the Harness interface for the Hermes agent runtime
// (NousResearch/hermes-agent). Hermes uses YAML config at /opt/data/config.yaml,
// identity in /opt/data/SOUL.md, and runs its gateway on port 8642.
type HermesHarness struct{}

func (h *HermesHarness) Name() string               { return "hermes" }
func (h *HermesHarness) DefaultImage() string       { return "nousresearch/hermes-agent:latest" }
func (h *HermesHarness) GatewayPort() int32         { return 8642 }
func (h *HermesHarness) HomePath() string           { return "/opt/data" }
func (h *HermesHarness) WorkspacePath() string      { return "/opt/data/skills" }
func (h *HermesHarness) ExtensionsPath() string     { return "/opt/data/plugins" }
func (h *HermesHarness) ConfigFileName() string     { return "config.yaml" }
func (h *HermesHarness) ConfigMapSuffix() string    { return "-hermes-config" }
func (h *HermesHarness) ReadinessPath() string      { return "" }
func (h *HermesHarness) LivenessPath() string       { return "" }
func (h *HermesHarness) ContainerName() string      { return "hermes" }
func (h *HermesHarness) ContainerCommand() []string { return []string{"hermes", "gateway", "run"} }
func (h *HermesHarness) RunAsUser() *int64          { return nil }

func (h *HermesHarness) CopyExtensionsCommands() []string {
	// Hermes has no baked-in extensions dir to copy. Plugins are Python-based
	// and installed at runtime. Just ensure the plugin directory exists.
	return []string{
		"mkdir -p /harness-home/plugins",
		"echo 'hermes plugin dir ready'",
	}
}

func (h *HermesHarness) SeedCommands() []string {
	// Hermes expects:
	//   /opt/data/config.yaml   — main config
	//   /opt/data/.env          — gateway env vars (allow all users, enable API)
	//   /opt/data/SOUL.md       — agent personality
	//   /opt/data/memories/USER.md — user context
	//   /opt/data/skills/<category>/SKILL.md — skills
	return []string{
		"mkdir -p /harness-home/memories /harness-home/skills /harness-home/plugins",
		fmt.Sprintf("cp /config-src/%s /harness-home/%s", h.ConfigFileName(), h.ConfigFileName()),
		// Hermes gateway needs a .env to enable the HTTP API and allow access.
		"echo 'GATEWAY_ALLOW_ALL_USERS=true' > /harness-home/.env",
		"echo 'GATEWAY_HTTP_ENABLED=true' >> /harness-home/.env",
		"cp /config-src/HEARTBEAT.md /harness-home/skills/HEARTBEAT.md 2>/dev/null || true",
		"cp /identity-src/SOUL.md /harness-home/SOUL.md 2>/dev/null || true",
		"cp /identity-src/USER.md /harness-home/memories/USER.md 2>/dev/null || true",
		"cp /identity-src/IDENTITY.md /harness-home/memories/IDENTITY.md 2>/dev/null || true",
		`for f in /skills-src/*; do [ -f "$f" ] && skill=$(basename "$f") && mkdir -p /harness-home/skills/$skill && cp "$f" /harness-home/skills/$skill/SKILL.md; done || true`,
		"echo 'hermes workspace seeded'",
	}
}

// BuildConfig generates a valid Hermes config.yaml from CRD data.
func (h *HermesHarness) BuildConfig(input ConfigInput) (string, error) {
	agent := input.Agent
	name := input.Name

	var b strings.Builder

	b.WriteString("# Hermes Agent config — generated by Clawbernetes operator\n")
	b.WriteString(fmt.Sprintf("# Agent: %s\n\n", name))

	// Model configuration
	if agent.Spec.Model.Provider != "" {
		b.WriteString("model:\n")
		b.WriteString(fmt.Sprintf("  provider: %s\n", hermesProviderName(agent.Spec.Model.Provider)))
		if agent.Spec.Model.Name != "" {
			b.WriteString(fmt.Sprintf("  model: %s\n", agent.Spec.Model.Name))
		}
		envVar := fmt.Sprintf("${%s_API_KEY}", strings.ToUpper(strings.ReplaceAll(agent.Spec.Model.Provider, "-", "_")))
		b.WriteString(fmt.Sprintf("  api_key: %s\n", envVar))
		b.WriteString("\n")
	}

	// Gateway configuration
	b.WriteString("gateway:\n")
	b.WriteString(fmt.Sprintf("  port: %d\n", h.GatewayPort()))
	b.WriteString("  host: 0.0.0.0\n")
	b.WriteString("\n")

	// Terminal backend — use local inside container
	b.WriteString("terminal:\n")
	b.WriteString("  backend: local\n")
	b.WriteString("\n")

	// Memory settings
	b.WriteString("memory:\n")
	b.WriteString("  limit: 100000\n")
	b.WriteString("  user_profile_tokens: 2000\n")
	b.WriteString("\n")

	// Security
	b.WriteString("security:\n")
	b.WriteString("  redact_secrets: true\n")
	b.WriteString("\n")

	// Channel configuration from ClawChannel CRs
	if len(input.Channels) > 0 {
		b.WriteString("channels:\n")
		for _, ch := range input.Channels {
			chType := ch.Spec.Type
			upperType := strings.ToUpper(chType)
			b.WriteString(fmt.Sprintf("  %s:\n", chType))
			b.WriteString("    enabled: true\n")
			if clawv1.ChannelsWithBotToken[chType] {
				b.WriteString(fmt.Sprintf("    bot_token: ${%s_BOT_TOKEN}\n", upperType))
			}
			if clawv1.ChannelsWithAppToken[chType] {
				b.WriteString(fmt.Sprintf("    app_token: ${%s_APP_TOKEN}\n", upperType))
			}
			for k, v := range ch.Spec.Config {
				b.WriteString(fmt.Sprintf("    %s: %s\n", k, v))
			}
		}
		b.WriteString("\n")
	}

	// OTEL diagnostics
	if input.OTLPEndpoint != "" {
		b.WriteString("diagnostics:\n")
		b.WriteString("  otel:\n")
		b.WriteString("    enabled: true\n")
		b.WriteString(fmt.Sprintf("    endpoint: %s\n", input.OTLPEndpoint))
		b.WriteString(fmt.Sprintf("    service_name: %s\n", name))
		b.WriteString("\n")
	}

	return b.String(), nil
}

// hermesProviderName maps Clawbernetes provider names to Hermes provider identifiers.
func hermesProviderName(provider string) string {
	switch provider {
	case "anthropic":
		return "anthropic"
	case "openai":
		return "openai"
	case "google":
		return "google"
	default:
		// Hermes supports OpenRouter as a universal fallback
		return provider
	}
}
