/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package harness

import (
	"fmt"
	"strings"

	clawv1 "github.com/clawbernetes/operator/api/v1"
)

// IronClawHarness implements the Harness interface for the IronClaw agent runtime
// (nearai/ironclaw). IronClaw is a Rust-based agent with WASM-sandboxed tools,
// .env bootstrap config, and a web gateway on port 3000.
type IronClawHarness struct{}

func (h *IronClawHarness) Name() string               { return "ironclaw" }
func (h *IronClawHarness) DefaultImage() string       { return "nearaidev/ironclaw:latest" }
func (h *IronClawHarness) GatewayPort() int32         { return 8080 }
func (h *IronClawHarness) HomePath() string           { return "/root/.ironclaw" }
func (h *IronClawHarness) WorkspacePath() string      { return "/root/.ironclaw" }
func (h *IronClawHarness) ExtensionsPath() string     { return "/root/.ironclaw/channels" }
func (h *IronClawHarness) ConfigFileName() string     { return ".env" }
func (h *IronClawHarness) ConfigMapSuffix() string    { return "-ironclaw-config" }
func (h *IronClawHarness) ReadinessPath() string      { return "" }
func (h *IronClawHarness) LivenessPath() string       { return "" }
func (h *IronClawHarness) ContainerName() string      { return "ironclaw" }
func (h *IronClawHarness) ContainerCommand() []string { return nil }
func (h *IronClawHarness) RunAsUser() *int64          { return nil }

func (h *IronClawHarness) CopyExtensionsCommands() []string {
	// IronClaw uses WASM-based tools built on demand — no extensions to copy.
	// Just ensure the data directory structure exists.
	return []string{
		"mkdir -p /harness-home/channels",
		"echo 'ironclaw data dir ready'",
	}
}

func (h *IronClawHarness) SeedCommands() []string {
	// IronClaw expects:
	//   ~/.ironclaw/.env          — bootstrap env vars (LLM_BACKEND, API keys, ports)
	//   ~/.ironclaw/channels/     — channel capability configs
	//   Identity files placed in workspace root for agent context
	return []string{
		"mkdir -p /harness-home/channels",
		fmt.Sprintf("cp /config-src/%s /harness-home/%s", h.ConfigFileName(), h.ConfigFileName()),
		"cp /identity-src/SOUL.md /harness-home/AGENTS.md 2>/dev/null || true",
		"cp /identity-src/USER.md /harness-home/USER.md 2>/dev/null || true",
		"cp /identity-src/IDENTITY.md /harness-home/IDENTITY.md 2>/dev/null || true",
		"cp /config-src/HEARTBEAT.md /harness-home/HEARTBEAT.md 2>/dev/null || true",
		`for f in /skills-src/*; do [ -f "$f" ] && cp "$f" /harness-home/$(basename "$f"); done || true`,
		"echo 'ironclaw workspace seeded'",
	}
}

// BuildConfig generates a valid IronClaw .env bootstrap file from CRD data.
func (h *IronClawHarness) BuildConfig(input ConfigInput) (string, error) {
	agent := input.Agent
	name := input.Name

	var b strings.Builder

	b.WriteString("# IronClaw bootstrap config — generated by Clawbernetes operator\n")
	b.WriteString(fmt.Sprintf("# Agent: %s\n\n", name))

	// LLM backend
	if agent.Spec.Model.Provider != "" {
		b.WriteString(fmt.Sprintf("LLM_BACKEND=%s\n", ironclawBackendName(agent.Spec.Model.Provider)))
		envVar := fmt.Sprintf("${%s_API_KEY}", strings.ToUpper(strings.ReplaceAll(agent.Spec.Model.Provider, "-", "_")))
		b.WriteString(fmt.Sprintf("%s_API_KEY=%s\n", strings.ToUpper(strings.ReplaceAll(agent.Spec.Model.Provider, "-", "_")), envVar))
	} else {
		b.WriteString("LLM_BACKEND=near_ai\n")
	}
	b.WriteString("\n")

	// Network — HTTP API on 8080 (0.0.0.0), web UI on 3000 (localhost only)
	b.WriteString("HTTP_HOST=0.0.0.0\n")
	b.WriteString(fmt.Sprintf("HTTP_PORT=%d\n", h.GatewayPort()))
	b.WriteString("WEB_GATEWAY_PORT=3000\n")
	b.WriteString("\n")

	// Agent settings
	b.WriteString("AGENT_MAX_PARALLEL_JOBS=5\n")
	b.WriteString("AGENT_JOB_TIMEOUT_SECS=3600\n")
	b.WriteString("AGENT_USE_PLANNING=true\n")
	b.WriteString("AGENT_STUCK_THRESHOLD_SECS=300\n")
	b.WriteString("\n")

	// Safety
	b.WriteString("INJECTION_CHECK_ENABLED=true\n")
	b.WriteString("MAX_OUTPUT_CHARS=100000\n")
	b.WriteString("LOG_LEVEL=info\n")
	b.WriteString("\n")

	// Self-repair
	b.WriteString("SELF_REPAIR_CHECK_INTERVAL_SECS=60\n")
	b.WriteString("SELF_REPAIR_MAX_ATTEMPTS=3\n")
	b.WriteString("\n")

	// Docker sandbox policy
	b.WriteString("DOCKER_POLICY=workspace_write\n")
	b.WriteString("DOCKER_MEMORY_LIMIT_MB=2048\n")
	b.WriteString("DOCKER_TIMEOUT_SECS=120\n")
	b.WriteString("\n")

	// OTEL
	if input.OTLPEndpoint != "" {
		b.WriteString(fmt.Sprintf("OTEL_EXPORTER_OTLP_ENDPOINT=%s\n", input.OTLPEndpoint))
		b.WriteString(fmt.Sprintf("OTEL_SERVICE_NAME=%s\n", name))
		b.WriteString("\n")
	}

	// Channel tokens from ClawChannel CRs
	for _, ch := range input.Channels {
		chType := strings.ToUpper(ch.Spec.Type)
		if clawv1.ChannelsWithBotToken[ch.Spec.Type] {
			b.WriteString(fmt.Sprintf("%s_BOT_TOKEN=${%s_BOT_TOKEN}\n", chType, chType))
		}
	}

	return b.String(), nil
}

// ironclawBackendName maps Clawbernetes provider names to IronClaw LLM_BACKEND values.
func ironclawBackendName(provider string) string {
	switch provider {
	case "anthropic":
		return "anthropic"
	case "openai":
		return "openai"
	case "google":
		return "google"
	default:
		return "openai_compatible"
	}
}
